apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: airbyte-abctl
    meta.helm.sh/release-namespace: airbyte-abctl
  creationTimestamp: "2025-02-21T08:56:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: airbyte-abctl
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: worker
    app.kubernetes.io/version: 1.5.0
    helm.sh/chart: worker-1.5.0
  name: airbyte-abctl-worker
  namespace: airbyte-abctl
  resourceVersion: "1133"
  uid: f0b686c5-9399-4977-b7e1-cff19a632251
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: airbyte-abctl
      app.kubernetes.io/name: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: airbyte-abctl
        app.kubernetes.io/name: worker
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: AIRBYTE_VERSION
          valueFrom:
            configMapKeyRef:
              key: AIRBYTE_VERSION
              name: airbyte-abctl-airbyte-env
        - name: AIRBYTE_EDITION
          valueFrom:
            configMapKeyRef:
              key: AIRBYTE_EDITION
              name: airbyte-abctl-airbyte-env
        - name: CONFIG_ROOT
          valueFrom:
            configMapKeyRef:
              key: CONFIG_ROOT
              name: airbyte-abctl-airbyte-env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: LOG_LEVEL
              name: airbyte-abctl-airbyte-env
        - name: MICROMETER_METRICS_ENABLED
          valueFrom:
            configMapKeyRef:
              key: MICROMETER_METRICS_ENABLED
              name: airbyte-abctl-airbyte-env
        - name: MICROMETER_METRICS_STEP
          valueFrom:
            configMapKeyRef:
              key: MICROMETER_METRICS_STEP
              name: airbyte-abctl-airbyte-env
        - name: MICROMETER_METRICS_OTLP_ENABLED
          valueFrom:
            configMapKeyRef:
              key: MICROMETER_METRICS_OTLP_ENABLED
              name: airbyte-abctl-airbyte-env
        - name: OTEL_COLLECTOR_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: OTEL_COLLECTOR_ENDPOINT
              name: airbyte-abctl-airbyte-env
        - name: MICROMETER_METRICS_STATSD_ENABLED
          valueFrom:
            configMapKeyRef:
              key: MICROMETER_METRICS_STATSD_ENABLED
              name: airbyte-abctl-airbyte-env
        - name: MICROMETER_METRICS_STATSD_FLAVOR
          valueFrom:
            configMapKeyRef:
              key: MICROMETER_METRICS_STATSD_FLAVOR
              name: airbyte-abctl-airbyte-env
        - name: SEGMENT_WRITE_KEY
          valueFrom:
            configMapKeyRef:
              key: SEGMENT_WRITE_KEY
              name: airbyte-abctl-airbyte-env
        - name: STATSD_HOST
          valueFrom:
            configMapKeyRef:
              key: STATSD_HOST
              name: airbyte-abctl-airbyte-env
        - name: STATSD_PORT
          valueFrom:
            configMapKeyRef:
              key: STATSD_PORT
              name: airbyte-abctl-airbyte-env
        - name: TRACKING_STRATEGY
          valueFrom:
            configMapKeyRef:
              key: TRACKING_STRATEGY
              name: airbyte-abctl-airbyte-env
        - name: WORKSPACE_DOCKER_MOUNT
          value: workspace
        - name: WORKSPACE_ROOT
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_ROOT
              name: airbyte-abctl-airbyte-env
        - name: WEBAPP_URL
          valueFrom:
            configMapKeyRef:
              key: WEBAPP_URL
              name: airbyte-abctl-airbyte-env
        - name: TEMPORAL_HOST
          valueFrom:
            configMapKeyRef:
              key: TEMPORAL_HOST
              name: airbyte-abctl-airbyte-env
        - name: TEMPORAL_WORKER_PORTS
          valueFrom:
            configMapKeyRef:
              key: TEMPORAL_WORKER_PORTS
              name: airbyte-abctl-airbyte-env
        - name: JOB_KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: JOB_MAIN_CONTAINER_CPU_REQUEST
          valueFrom:
            configMapKeyRef:
              key: JOB_MAIN_CONTAINER_CPU_REQUEST
              name: airbyte-abctl-airbyte-env
        - name: JOB_MAIN_CONTAINER_CPU_LIMIT
          valueFrom:
            configMapKeyRef:
              key: JOB_MAIN_CONTAINER_CPU_LIMIT
              name: airbyte-abctl-airbyte-env
        - name: JOB_MAIN_CONTAINER_MEMORY_REQUEST
          valueFrom:
            configMapKeyRef:
              key: JOB_MAIN_CONTAINER_MEMORY_REQUEST
              name: airbyte-abctl-airbyte-env
        - name: JOB_MAIN_CONTAINER_MEMORY_LIMIT
          valueFrom:
            configMapKeyRef:
              key: JOB_MAIN_CONTAINER_MEMORY_LIMIT
              name: airbyte-abctl-airbyte-env
        - name: INTERNAL_API_HOST
          valueFrom:
            configMapKeyRef:
              key: INTERNAL_API_HOST
              name: airbyte-abctl-airbyte-env
        - name: WORKLOAD_API_HOST
          valueFrom:
            configMapKeyRef:
              key: WORKLOAD_API_HOST
              name: airbyte-abctl-airbyte-env
        - name: WORKLOAD_API_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              key: WORKLOAD_API_BEARER_TOKEN
              name: airbyte-abctl-airbyte-secrets
        - name: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
          valueFrom:
            configMapKeyRef:
              key: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
              name: airbyte-abctl-airbyte-env
        - name: JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
          valueFrom:
            configMapKeyRef:
              key: JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
              name: airbyte-abctl-airbyte-env
        - name: ACTIVITY_MAX_ATTEMPT
          valueFrom:
            configMapKeyRef:
              key: ACTIVITY_MAX_ATTEMPT
              name: airbyte-abctl-airbyte-env
        - name: ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS
          valueFrom:
            configMapKeyRef:
              key: ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS
              name: airbyte-abctl-airbyte-env
        - name: ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS
          valueFrom:
            configMapKeyRef:
              key: ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS
              name: airbyte-abctl-airbyte-env
        - name: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
          valueFrom:
            configMapKeyRef:
              key: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
              name: airbyte-abctl-airbyte-env
        - name: SHOULD_RUN_NOTIFY_WORKFLOWS
          valueFrom:
            configMapKeyRef:
              key: SHOULD_RUN_NOTIFY_WORKFLOWS
              name: airbyte-abctl-airbyte-env
        - name: MICRONAUT_ENVIRONMENTS
          valueFrom:
            configMapKeyRef:
              key: WORKERS_MICRONAUT_ENVIRONMENTS
              name: airbyte-abctl-airbyte-env
        - name: AIRBYTE_API_AUTH_HEADER_NAME
          value: X-Airbyte-Auth
        - name: AIRBYTE_API_AUTH_HEADER_VALUE
          value: Internal worker
        - name: SECRET_PERSISTENCE
        - name: S3_PATH_STYLE_ACCESS
          valueFrom:
            configMapKeyRef:
              key: S3_PATH_STYLE_ACCESS
              name: airbyte-abctl-airbyte-env
        - name: STORAGE_TYPE
          value: MINIO
        - name: STORAGE_BUCKET_ACTIVITY_PAYLOAD
          valueFrom:
            configMapKeyRef:
              key: STORAGE_BUCKET_ACTIVITY_PAYLOAD
              name: airbyte-abctl-airbyte-env
        - name: STORAGE_BUCKET_LOG
          valueFrom:
            configMapKeyRef:
              key: STORAGE_BUCKET_LOG
              name: airbyte-abctl-airbyte-env
        - name: STORAGE_BUCKET_STATE
          valueFrom:
            configMapKeyRef:
              key: STORAGE_BUCKET_STATE
              name: airbyte-abctl-airbyte-env
        - name: STORAGE_BUCKET_WORKLOAD_OUTPUT
          valueFrom:
            configMapKeyRef:
              key: STORAGE_BUCKET_WORKLOAD_OUTPUT
              name: airbyte-abctl-airbyte-env
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: MINIO_ACCESS_KEY_ID
              name: airbyte-abctl-airbyte-secrets
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: MINIO_SECRET_ACCESS_KEY
              name: airbyte-abctl-airbyte-secrets
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: MINIO_ENDPOINT
              name: airbyte-abctl-airbyte-env
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: DATABASE_HOST
              name: airbyte-abctl-airbyte-env
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PORT
              name: airbyte-abctl-airbyte-env
        - name: DATABASE_DB
          valueFrom:
            configMapKeyRef:
              key: DATABASE_DB
              name: airbyte-abctl-airbyte-env
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: DATABASE_USER
              name: airbyte-abctl-airbyte-secrets
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: airbyte-abctl-airbyte-secrets
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: airbyte-abctl-airbyte-env
        - name: AIRBYTE_INSTALLATION_ID
          value: f863577c-b34e-48ae-ada0-66a0ffd064e8
        - name: CONTAINER_ORCHESTRATOR_ENABLED
          value: "true"
        image: airbyte/worker:1.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: heartbeat
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: airbyte-worker-container
        ports:
        - containerPort: 9000
          name: heartbeat
          protocol: TCP
        - containerPort: 9001
          protocol: TCP
        - containerPort: 9002
          protocol: TCP
        - containerPort: 9003
          protocol: TCP
        - containerPort: 9004
          protocol: TCP
        - containerPort: 9005
          protocol: TCP
        - containerPort: 9006
          protocol: TCP
        - containerPort: 9007
          protocol: TCP
        - containerPort: 9008
          protocol: TCP
        - containerPort: 9009
          protocol: TCP
        - containerPort: 9010
          protocol: TCP
        - containerPort: 9011
          protocol: TCP
        - containerPort: 9012
          protocol: TCP
        - containerPort: 9013
          protocol: TCP
        - containerPort: 9014
          protocol: TCP
        - containerPort: 9015
          protocol: TCP
        - containerPort: 9016
          protocol: TCP
        - containerPort: 9017
          protocol: TCP
        - containerPort: 9018
          protocol: TCP
        - containerPort: 9019
          protocol: TCP
        - containerPort: 9020
          protocol: TCP
        - containerPort: 9021
          protocol: TCP
        - containerPort: 9022
          protocol: TCP
        - containerPort: 9023
          protocol: TCP
        - containerPort: 9024
          protocol: TCP
        - containerPort: 9025
          protocol: TCP
        - containerPort: 9026
          protocol: TCP
        - containerPort: 9027
          protocol: TCP
        - containerPort: 9028
          protocol: TCP
        - containerPort: 9029
          protocol: TCP
        - containerPort: 9030
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: heartbeat
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            memory: "512Mi"  # Set based on expected usage
            cpu: "500m"      # Adjust accordingly
          limits:
            memory: "2Gi"    # Set appropriate limits
            cpu: "2"         # Adjust accordingly
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: airbyte-admin
      serviceAccountName: airbyte-admin
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-21T08:58:52Z"
    lastUpdateTime: "2025-02-21T08:58:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-21T08:56:31Z"
    lastUpdateTime: "2025-02-21T08:58:52Z"
    message: ReplicaSet "airbyte-abctl-worker-765b474559" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
