version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: weather_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - weather-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 20s  # Give PostgreSQL some time to start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - jaeger
  
  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    platform: linux/amd64
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:mysecretpassword@postgres-db:5432/weather_db?sslmode=disable
    ports:
      - "9187:9187"  # PostgreSQL exporter metrics port
    networks:
      - weather-network

  weather-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: weather-app
    environment:
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      DB_HOST: postgres
      DB_NAME: weather_db
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    depends_on:
      postgres:
        condition: service_healthy  # Wait for PostgreSQL health check to pass
    networks:
      - weather-network
    restart: always
    volumes:
      - app_data:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "9089:9089"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - weather-network
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile
    image: clickhous
    container_name: clickhouse
    hostname: clickhouse-host
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9009:9009"
    volumes:
      - ./odbc.ini:/etc/odbc.ini
      - ./odbcinst.ini:/etc/odbcinst.ini
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs:/var/log/clickhouse-server 
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password
    restart: always
    networks:
      - weather-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 4g

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888   # pprof extension
      - 8888:8888   # Prometheus metrics exposed by the Collector
      - 8889:8889   # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 55679:55679 # zpages extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    depends_on:
      - jaeger
    networks:
      - weather-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "6831:6831/udp"   # UDP port for Jaeger agent
      - "16686:16686"     # Web UI
      - "14268:14268"     # HTTP port for spans
      - "14250:14250"     # gRPC for Jaeger collector
      - "6832:6832/udp"
      - "5778:5778"
      - "5775:5775"
      - 9411:9411
    networks:
      - weather-network
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  prometheus: 
    image: prom/prometheus:latest
    container_name: "prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - weather-network

volumes:
  postgres_data:
  app_data:

networks:
  weather-network:
    driver: bridge
