global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889'] 

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']

  - job_name: 'weather-app'
    static_configs:
      - targets: ['weather-app:9089']
