global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090'] # OpenTelemetry Collector Prometheus exporter

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-odbc:9000']

  - job_name: 'weather-app'
    static_configs:
      - targets: ['weather-app:8000']
